-- ============================================================
-- Post-deploy cron: evitar que Supabase pause el proyecto por inactividad
-- (pg_cron + pg_net)
--
-- Supabase pausa los proyectos del plan gratuito si no detecta actividad de
-- base de datos en los ultimos 7 dias. Este job pega dos veces por dia a un
-- endpoint que hace un SELECT de solo-lectura (sin INSERT/UPDATE/DELETE) —
-- de sobra para contar como actividad, sin crear datos falsos ni tocar
-- ninguna tabla de negocio.
--
-- WHY this is not a migration: the job needs your live prod URL and CRON_SECRET,
-- which only exist AFTER the first Vercel deploy. The extensions it relies on are
-- enabled by migration 20260615000003_enable_pg_cron_pg_net (applied via db push).
--
-- HOW to run: replace the two placeholders with the values from your .env.local,
-- then run this in the Supabase dashboard -> SQL Editor. (scripts/setup.mjs can
-- fill it for you and print the ready-to-paste SQL — see `cron-sql keep-alive`.)
-- It is idempotent: re-running updates the existing 'keep-alive' job in place.
--
--   __APP_URL__      -> NEXT_PUBLIC_APP_URL  (e.g. https://your-app.vercel.app -- NO trailing slash)
--   __CRON_SECRET__  -> CRON_SECRET          (hex secret generated by scripts/setup.mjs)
-- ============================================================

select cron.schedule(
  'keep-alive',              -- unique job name; re-scheduling updates it in place
  '13 4,16 * * *',           -- twice a day (04:13 and 16:13 UTC) — well within
                              -- Supabase's "a few requests a day" threshold
  $job$
    select net.http_get(
      url     := '__APP_URL__/api/cron/keep-alive',
      headers := jsonb_build_object('Authorization', 'Bearer __CRON_SECRET__')
    );
  $job$
);

-- Verify it registered (expect one active row):
--   select jobname, schedule, active from cron.job where jobname = 'keep-alive';
--
-- Inspect recent runs / failures:
--   select status, return_message, start_time
--   from cron.job_run_details
--   where jobid = (select jobid from cron.job where jobname = 'keep-alive')
--   order by start_time desc limit 10;
--
-- Remove the job:
--   select cron.unschedule('keep-alive');
